$(function(){"use strict";$("#search-button").click(function(){$("#search-box").toggleClass("active hvr-underline-from-center").focus;$(this).toggleClass("animate");$("search-input").val("");});$('.latest-news').slick({autoplay:true,autoplaySpeed:4500,cssEase:'linear',slidesToShow:4,slidesToScroll:1,pauseOnHover:false,vertical:true,dots:false,prevArrow:$('#last-news-controls > .next'),nextArrow:$('#last-news-controls >.prev'),});$('.sponsored-article').slick({autoplay:true,autoplaySpeed:4500,cssEase:'linear',slidesToShow:3,slidesToScroll:1,pauseOnHover:false,vertical:true,dots:false,prevArrow:$('#latest-news > .next'),nextArrow:$('#latest-news >.prev'),});$('.extra-news-area').slick({autoplay:true,infinite:true,slidesToShow:5,centerPadding:'60px',rtl:true,slidesToScroll:1,prevArrow:$('#extra-news-previus-controls > .next'),nextArrow:$('#extra-news-previus-controls >.prev'),responsive:[{breakpoint:768,settings:{arrows:false,centerMode:true,centerPadding:'0',slidesToShow:1}},]});$('.other-videos').slick({autoplay:true,autoplaySpeed:5000,cssEase:'linear',slidesToShow:3,slidesToScroll:1,pauseOnHover:false,vertical:true,dots:false,prevArrow:$('#other-videos > .next'),nextArrow:$('#other-videos >.prev'),});$('.highlighted-videos').slick({autoplay:true,autoplaySpeed:4500,cssEase:'linear',slidesToShow:3,slidesToScroll:1,pauseOnHover:false,rtl:false,vertical:false,dots:false,prevArrow:$('#highlighted-videos > .next'),nextArrow:$('#highlighted-videos > .prev'),responsive:[{breakpoint:768,settings:{arrows:false,centerMode:true,centerPadding:'0',slidesToShow:1}},]});$('#btn-ticker-news').click(function(){$("#latest-news").toggleClass("ticker-news-hide");});$('.hot-news-list').easyTicker({direction:'up',easing:'swing',speed:'slow',interval:4000,height:'auto',visible:1,mousePause:false,});$('.event-now-list').easyTicker({direction:'up',easing:'swing',speed:'slow',interval:5000,height:'auto',visible:1,mousePause:false,});$('.latest-news-list').easyTicker({direction:'down',easing:'swing',speed:'slow',interval:5000,height:'auto',visible:1,mousePause:false,controls:{up:'',down:'',toggle:'',playText:'Play',stopText:'Stop'},callbacks:{before:false,after:false,finish:false}});$('.important-info-list').easyTicker({direction:'up',easing:'swing',speed:'slow',interval:5000,height:'auto',visible:1,mousePause:false,});$('.btn-close-ticker').click(function(){var area=$(this).closest('.ticker');if(area){area.toggleClass("ticker-news-hide");}});function change_weather_wilaya(){alert("1111");}
$('#btn-1').click(function(){$("#ticker-hotnews").toggleClass("ticker-news-hide");});$('#btn-2').click(function(){$("#event-now-news").toggleClass("ticker-news-hide");});$('#btn-3').click(function(){$("#latest-news").toggleClass("ticker-news-hide");});$('#btn-4').click(function(){$("#important-event").toggleClass("ticker-news-hide");});$('.news-ticker').hide();setTimeout(function(){$('.news-ticker').show();},1000);$(".fancybox").fancybox();$("#pdf_link").on("click",function(e){console.log("bananas");$('.bs-example-modal-lg').modal('show');$('div.modal-backdrop').css('z-index',0);e.preventDefault();})
$(".fancybox").fancybox();$(".nav_search").on("click",function(e){$("#search_overlay").show().css("display","flex");$("#search_form input").focus();e.preventDefault();})
$(".relative_time").timeago();$("body").on("click",".captcha_refresh",function(e){e.preventDefault();d=new Date();$(this).parents(".comment_form").find(".comments_captcha>img").attr('src','/captcha/?'+d.getTime());})
$("#font_up, #font_down").on("click",function(e){e.preventDefault();var id=$(this).attr("id");var size=$("#article_body").css("font-size");if(id=="font_up"){var incr=2;$("#article_body").css("font-size",parseInt(size)+2+"px");}else{var incr=-2;$("#article_body").css("font-size",parseInt(size)-2+"px");}
console.log("1",incr);if(document.cookie.indexOf("commfz")>-1){var fsize=document.cookie.substring(document.cookie.indexOf("commfz")+7);console.log("2",fsize);if(fsize.indexOf(";")>-1){fsize=fsize.substring(0,fsize.indexOf(";"));}
fsize=parseInt(fsize)+incr;}else{fsize=incr;}
console.log("3",fsize);var time=new Date;time.setFullYear(time.getFullYear()+1);document.cookie="commfz="+fsize+"; expires="+time.toGMTString()+'; path=/';})
if(document.cookie.indexOf("commfz")>-1){var fsize=document.cookie.substring(document.cookie.indexOf("commfz")+7);if(fsize.indexOf(";")>-1){fsize=fsize.substring(0,fsize.indexOf(";"));}
fsize=parseInt($("#article_wrapper #article_body").css("font-size"))+parseInt(fsize);$("#article_wrapper #article_body").css("font-size",fsize);}
$("body").on("click","#poll .poll_choice",function(e){$("#poll .chosen").removeClass("chosen");$(this).addClass("chosen");e.preventDefault();})});